json.title movie.title
json.year movie.year
json.rated movie.rated
json.released movie.released
json.runtime movie.runtime
json.genre movie.genre
json.director movie.director
json.writer movie.writer
json.actors movie.actors
json.plot movie.plot
json.language movie.language
json.country movie.country
json.awards movie.awards
json.poster movie.poster
json.created_at movie.created_at
json.updated_at movie.updated_at